word_embedding_size  : [100]
tag_embedding_size   : [100]
encoder_dropout : [0.5]
mlp_input           : 400 
mlp_arc_hidden  : [500] 
mlp_lab_hidden  : 100 
mlp_dropout       : [0.5]
word_dropout     : [0.5]
batch_size          :  64
epochs                : 70
lexer                   : 'default'
device                 : 'cuda:2'
output_path        : 'preds' 
