word_embedding_size  : [100]
tag_embedding_size   : [100]
encoder_dropout : [0.2]
mlp_input           : 400 
mlp_arc_hidden  : [500] 
mlp_lab_hidden  : 100 
mlp_dropout       : [0.5]
word_dropout     : [0.2]
batch_size          :  64
epochs                :  100
lexer                   : 'default'
device                 : 'cuda:2'
ouptut_file          : 'model_preds' 
