word_embedding_size : 100
char_embedding_size : 16
encoder_dropout     : 0.3
mlp_input           : 400
mlp_arc_hidden      : 400
mlp_lab_hidden      : 100
mlp_dropout         : 0.3
word_dropout        : 0.0
batch_size          : 2
epochs              : 100
lr                  : 0.001
lexer               : 'default'
device              : 'cuda:3'
